Repository doctrine/DoctrineBundle, pull requests merged in 2019-12, with the labels that each got.

#1095 Fix doctrine deprecations
  Command/DoctrineCommand.php
  Command/ImportMappingDoctrineCommand.php
  Command/Proxy/DelegateCommand.php
  DataCollector/DoctrineDataCollector.php
  DependencyInjection/DoctrineExtension.php
  Mapping/DisconnectedMetadataFactory.php
  Repository/ContainerRepositoryFactory.php
  Repository/ServiceEntityRepository.php
  Resources/config/dbal.xml
  Tests/Command/CreateDatabaseDoctrineTest.php
  Tests/Command/DropDatabaseDoctrineTest.php
  Tests/ConnectionFactoryTest.php
  Tests/ContainerTest.php
  Tests/DataCollector/DoctrineDataCollectorTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
  Tests/Mapping/DisconnectedMetadataFactoryTest.php
  Tests/ProfilerTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
  Tests/Repository/ServiceEntityRepositoryTest.php
  Tests/ServiceRepositoryTest.php
  Tests/TestCase.php
  composer.json
Labels: Improvement

#1087 Fix creating wrapped connection twice
  ConnectionFactory.php
  Tests/ConnectionFactoryTest.php
Labels: Bug

#1085 Allow non-scalar DBAL options
  DependencyInjection/Configuration.php
  Resources/config/schema/doctrine-1.0.xsd
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_service_multiple_connections.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_service_multiple_connections.yml
Labels: Bug

#1099 Make manager registry resettable
  Registry.php
  Resources/config/dbal.xml
  composer.json
Labels: Bug

#1103 Fix error when resetting manager registry
  Registry.php
  Tests/RegistryTest.php
Labels: Bug

#1106 Skip resetting managers when proxy-manager is not installed
  Registry.php
  Tests/RegistryTest.php
  composer.json
Labels: Bug

#1086 Activate selective stale probot
  .github/stale.yml
Labels: Improvement

#1108 Fix resetting non-lazy managers
  Registry.php
  Tests/RegistryTest.php
Labels: Bug

#1111 Don't mark milestoned issues as stale
  .github/stale.yml
Labels: CI
