Repository doctrine/DoctrineBundle, pull requests merged in 2019-02, with the labels that each got.

#906 Update examples in entity listeners documentation
  Resources/doc/entity-listeners.rst
Labels: Documentation

#915 Don't rewrite defaultTableOptions in sharded or master/slave connections
  DependencyInjection/DoctrineExtension.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_service_pool_sharding_connection.xml
  Tests/DependencyInjection/Fixtures/config/xml/dbal_service_single_master_slave_connection.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_service_pool_sharding_connection.yml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_service_single_master_slave_connection.yml
Labels: Bug

#912 Updated the value of path option to match the official recipe
  Resources/doc/configuration.rst
Labels: Documentation

#905 CI: Use Ubuntu 16.04
  .travis.yml
Labels: Improvement

#910 Made entity listener documentation less ambiguous
  Resources/doc/entity-listeners.rst
Labels: Documentation

#919 provide better error when doctrine/orm is missing
  DependencyInjection/Configuration.php
Labels: Improvement

#913 Added some missing contents to an XML config sample
  Resources/doc/configuration.rst
Labels: Documentation

#920 Test against PHP 7.4snapshot instead of nightly (8.0)
  .travis.yml
Labels: Improvement

#922 remove OTV
  DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
Labels: Improvement

#923 fix php doc
  DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
Labels: Improvement

#924 remove useless phpdoc
  ConnectionFactory.php
  Controller/ProfilerController.php
  DataCollector/DoctrineDataCollector.php
  DependencyInjection/Configuration.php
  DoctrineBundle.php
  Mapping/ClassMetadataCollection.php
  Registry.php
Labels: Improvement
