Repository doctrine/DoctrineBundle, pull requests merged in 2019-04, with the labels that each got.

#929 Use namespaced Twig
  Tests/ProfilerTest.php
  Twig/DoctrineExtension.php
  composer.json
Labels: Improvement

#928 Drop support for Symfony < 3.4
  Registry.php
Labels: Improvement

#932 Updated doctrine/coding-standard to 6.0
  Controller/ProfilerController.php
  DataCollector/DoctrineDataCollector.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
  Twig/DoctrineExtension.php
  composer.json
Labels: Improvement

#943 [1.10] Don't fail build for the 3 known Twig deprecations
  .travis.yml
Labels: Improvement

#927 Fix php doc block
  Registry.php
Labels: Bug

#942 Update build pipeline
  .travis.yml
Labels: Improvement

#946 Add deprecation notices for container in DoctrineCommand
  Command/DoctrineCommand.php
Labels: Improvement

#944 Wire messenger transport factory
  DependencyInjection/DoctrineExtension.php
  Resources/config/messenger.xml
Labels: Feature

#939 Add support for validator auto-mapping
  DependencyInjection/DoctrineExtension.php
  Tests/ContainerTest.php
Labels: Feature

#935 Removing deprecated call to Configuration::setSchemaAssetsFilter() + extendable
  Dbal/RegexSchemaAssetFilter.php
  Dbal/SchemaAssetsFilterManager.php
  DependencyInjection/Compiler/DbalSchemaFilterPass.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/dbal.xml
  Tests/Dbal/RegexSchemaAssetFilterTest.php
  Tests/Dbal/SchemaAssetsFilterManagerTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_schema_filter.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_schema_filter.yml
Labels: Improvement

#948 Add symfony cache pool support
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/doc/configuration.rst
  Tests/DependencyInjection/DoctrineExtensionTest.php
  composer.json
Labels: Feature, ⭐️ EUFOSSA Hackathon

#950 abstain from registering incomplete services
  DependencyInjection/DoctrineExtension.php
Labels: Bug, ⭐️ EUFOSSA Hackathon

#951 Add ContainerEntityListenerResolver + load listeners lazy by default
  DependencyInjection/Compiler/EntityListenerPass.php
  Mapping/ContainerAwareEntityListenerResolver.php
  Mapping/ContainerEntityListenerResolver.php
  Resources/config/orm.xml
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/CustomEntityListenerServiceResolver.php
  Tests/DependencyInjection/Fixtures/config/xml/orm_attach_lazy_entity_listener.xml
  Tests/DependencyInjection/Fixtures/config/xml/orm_entity_listener_custom_resolver.xml
  Tests/DependencyInjection/Fixtures/config/yml/orm_attach_lazy_entity_listener.yml
  Tests/DependencyInjection/Fixtures/config/yml/orm_entity_listener_custom_resolver.yml
  Tests/DependencyInjection/Fixtures/config/yml/orm_entity_listener_resolver.yml
  Tests/Mapping/ContainerEntityListenerResolverTest.php
Labels: Feature, ⭐️ EUFOSSA Hackathon

#947 Deprecate type comment attribute from configuration
  ConnectionFactory.php
  DependencyInjection/Configuration.php
  Tests/ConnectionFactoryTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/TestCommentedType.php
  Tests/TestCase.php
  phpunit.xml.dist
Labels: ⭐️ EUFOSSA Hackathon

#955 Add new pool option to XSD
  Resources/config/schema/doctrine-1.0.xsd
Labels: Improvement

#956 ping/close connection middleware services
  Resources/config/messenger.xml
  Tests/DependencyInjection/DoctrineExtensionTest.php
Labels: Feature
