Repository doctrine/DoctrineBundle, pull requests merged in 2019-05, with the labels that each got.

#961 Test against Symfony 4.3 beta
  .travis.yml
Labels: Improvement

#954 [Profiling] Add query backtrace data
  Dbal/Logging/BacktraceLogger.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/dbal.xml
  Resources/config/schema/doctrine-1.0.xsd
  Resources/doc/configuration.rst
  Resources/views/Collector/db.html.twig
  Tests/Dbal/Logging/BacktraceLoggerTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_logging.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_logging.yml
Labels: Feature

#962 Linkify backtrace callstack
  Resources/views/Collector/db.html.twig
Labels: Improvement

#963 Add upgrade files
  UPGRADE-1.11.md
  UPGRADE-2.0.md
Labels: Documentation

#964 Fix non existent service when using symfony cache pools
  DependencyInjection/DoctrineExtension.php
Labels: Bug

#966 Fix schema filters
  DoctrineBundle.php
  Tests/BundleTest.php
Labels: Bug

#965 Wiring of the new PropertyAccessExtractor
  DependencyInjection/DoctrineExtension.php
Labels: Bug

#968 Skip generating link for backtrace record with missing file, fixes #967
  Resources/views/Collector/db.html.twig
Labels: Bug

#975 Allow Symfony 5.0
  .travis.yml
  composer.json
Labels: Improvement
