Repository doctrine/DoctrineBundle, pull requests merged in 2019-11, with the labels that each got.

#1043 Adding support for DoctrineClearEntityManagerWorkerSubscriber
  DependencyInjection/DoctrineExtension.php
  Resources/config/messenger.xml
  Tests/DependencyInjection/DoctrineExtensionTest.php
Labels: Feature

#1047 Fix compat with Symfony 5 after a recent deprecation
  .travis.yml
  DataCollector/DoctrineDataCollector.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Tests/ContainerTest.php
  composer.json
Labels: Improvement

#1042 Sort composer.json
  Tests/ServiceRepositoryTest.php
  composer.json
Labels: Improvement

#1049 Add new service alias for manager registry
  Repository/ServiceEntityRepository.php
  Resources/config/dbal.xml
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
Labels: Improvement

#1048 Remove aliases for common interfaces
  Resources/config/dbal.xml
  Resources/config/orm.xml
  Tests/DependencyInjection/DoctrineExtensionTest.php
  UPGRADE-2.0.md
Labels: Improvement

#1050 Restore autowiring alias for ManagerRegistry
  Repository/ServiceEntityRepository.php
  Resources/config/dbal.xml
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
  UPGRADE-2.0.md
Labels: Improvement

#1052 Deprecated alias for common interfaces
  Resources/config/dbal.xml
  Resources/config/orm.xml
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
  UPGRADE-1.12.md
Labels: Improvement

#1054 Fix deprecation failures around doctrine:mapping:import command
  Tests/Command/ImportMappingDoctrineCommandTest.php
Labels: Improvement

#1055 [DoctrineDataCollector] Handle runnable flag
  DataCollector/DoctrineDataCollector.php
  Resources/views/Collector/db.html.twig
Labels: Improvement

#1058 Use XMLBundle in container tests
  Tests/ContainerTest.php
  Tests/TestCase.php
Labels: Improvement

#1059 Add number-aware underscore naming strategy
  Resources/config/orm.xml
Labels: Improvement

#1070 Default to real-utf8 when no charset is provided
  ConnectionFactory.php
  Tests/ConnectionFactoryTest.php
  UPGRADE-2.0.md
Labels: Improvement

#1075 Use symfony/flex to lock Symfony dependencies to the same version
  .travis.yml
  composer.json
Labels: Improvement

#1073 Fix: use array adapter cache pools by default
  DependencyInjection/DoctrineExtension.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  composer.json
Labels: Bug

#1077 Default to real-utf8 when no charset is provided
  ConnectionFactory.php
  Tests/ConnectionFactoryTest.php
  UPGRADE-2.0.md
Labels: Improvement

#1079 Deprecated alias on DI Extension
  DependencyInjection/DoctrineExtension.php
  Resources/config/dbal.xml
  Resources/config/orm.xml
Labels: Bug
