Repository doctrine/DoctrineBundle, pull requests merged in 2020-01, with the labels that each got.

#1120 Add a feature switch to trigger SchemaValidator in Collector
  DataCollector/DoctrineDataCollector.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/dbal.xml
  Resources/config/schema/doctrine-1.0.xsd
  Resources/doc/configuration.rst
  Resources/views/Collector/db.html.twig
  Tests/DataCollector/DoctrineDataCollectorTest.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_logging.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_logging.yml
Labels: Feature

#1119 Added EventSubscriberInterface marker interface to support autoconfiguration
  DependencyInjection/DoctrineExtension.php
  EventSubscriber/EventSubscriberInterface.php
Labels: Improvement

#1118 Fix desynchronized entity managers after kernel reset
  Registry.php
  Tests/Command/ImportMappingDoctrineCommandTest.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomClassRepoRepository.php
  Tests/DependencyInjection/Fixtures/TestKernel.php
  Tests/RegistryTest.php
  composer.json
Labels: Bug

#1056 [WebProfiler] Add copy button on runnable and formatted queries
  Resources/views/Collector/db.html.twig
  Tests/ProfilerTest.php
  Twig/DoctrineExtension.php
Labels: Feature
