Repository doctrine/DoctrineBundle, pull requests merged in 2020-05, with the labels that each got.

#1161 Update Entity Listener Docs to New Service Style
  Resources/doc/entity-listeners.rst
Labels: Documentation

#1170 Add minimal compatibility with changes in DBAL 2.11 RunSqlCommand
  Command/Proxy/RunSqlDoctrineCommand.php
Labels: Bug

#1165 Update comment on the schema_filter key
  Resources/doc/configuration.rst
Labels: Documentation

#1167 Preload Autoloader class when the ORM is used
  DependencyInjection/DoctrineExtension.php
  Tests/DependencyInjection/Fixtures/config/yml/orm_service_single_entity_manager.yml
Labels: Improvement

#1172 Test against PHP 8
  .travis.yml
  composer.json
Labels: CI, Improvement

#1173 Allow DBAL 3.0 and ignore ORM tests on php 8
  .travis.yml
  Tests/Command/ImportMappingDoctrineCommandTest.php
  Tests/ContainerTest.php
  Tests/DataCollector/DoctrineDataCollectorTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  Tests/Mapping/ContainerEntityListenerResolverTest.php
  Tests/Mapping/DisconnectedMetadataFactoryTest.php
  Tests/RegistryTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
  Tests/Repository/ServiceEntityRepositoryTest.php
  Tests/ServiceRepositoryTest.php
  composer.json
Labels: CI
