Repository doctrine/DoctrineBundle, pull requests merged in 2021-03, with the labels that each got.

#1260 Fix bugs in PhpArrayAdapter introduction
  CacheWarmer/DoctrineMetadataCacheWarmer.php
  Command/Proxy/ClearMetadataCacheDoctrineCommand.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  UPGRADE-2.3.md
Labels: Improvement

#1290 add ability to override url with dsn params
  ConnectionFactory.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/schema/doctrine-1.0.xsd
  Resources/doc/configuration.rst
  Tests/ConnectionFactoryTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/DbalTestKernel.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_allow_partial_url_override.xml
  Tests/DependencyInjection/Fixtures/config/xml/dbal_allow_url_override.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_allow_partial_url_override.yml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_allow_url_override.yml
  Tests/UrlOverrideTest.php
  UPGRADE-2.3.md
Labels: Feature

#1309 Disable schema validation no matter the profiling configuration
  DependencyInjection/DoctrineExtension.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_collect_schema_errors_disable.xml
  Tests/DependencyInjection/Fixtures/config/xml/dbal_collect_schema_errors_disable_no_profiling.xml
  Tests/DependencyInjection/Fixtures/config/xml/dbal_collect_schema_errors_enable.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_collect_schema_errors_disable.yml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_collect_schema_errors_disable_no_profiling.yml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_collect_schema_errors_enable.yml
Labels: Bug, Needs Tests
