Repository doctrine/DoctrineBundle, pull requests merged in 2022-12, with the labels that each got.

#1586 Drop support for Symfony 4
  .github/workflows/continuous-integration.yml
  DependencyInjection/Compiler/CacheSchemaSubscriberPass.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/messenger.xml
  Tests/CacheSchemaSubscriberTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Compiler/MiddlewarePassTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  composer.json
Labels: Improvement

#1568 Add option "doctrine.orm.enable_lazy_ghost_objects"
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
Labels: Feature

#1598 Allow Annotations 2, add attribute support to testing fixtures and test with attributes when able, allow the Annotations package to be an optional dependency
  DependencyInjection/DoctrineExtension.php
  Tests/Command/ImportMappingDoctrineCommandTest.php
  Tests/Command/Proxy/InfoDoctrineCommandTest.php
  Tests/ContainerTest.php
  Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
  Tests/DependencyInjection/Compiler/IdGeneratorPassTest.php
  Tests/DependencyInjection/Fixtures/Bundles/AttributesBundle/Entity/TestCustomIdGeneratorEntity.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestCustomClassRepoEntity.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestCustomServiceRepoEntity.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestDefaultRepoEntity.php
  Tests/DependencyInjection/Fixtures/DbalTestKernel.php
  Tests/DependencyInjection/Fixtures/TestKernel.php
  Tests/RegistryTest.php
  Tests/ServiceRepositoryTest.php
  Tests/TestCase.php
  composer.json
Labels: Improvement

#1583 Add documentation for AsEventListener attribute
  Resources/doc/event-listeners.rst
  Resources/doc/index.rst
Labels: Feature, Documentation
