Repository doctrine/DoctrineBundle, pull requests merged in 2022-02, with the labels that each got.

#1471 Remap collate to collation when appropriate
  ConnectionFactory.php
  Tests/ConnectionFactoryTest.php
  composer.json
  psalm.xml.dist
Labels: Bug

#1479 Stop giving charset examples
  Resources/doc/configuration.rst
Labels: Documentation

#1472 Allow userland middlewares
  Attribute/AsMiddleware.php
  DependencyInjection/Compiler/MiddlewaresPass.php
  DependencyInjection/DoctrineExtension.php
  DoctrineBundle.php
  Middleware/ConnectionNameAwareInterface.php
  Resources/config/dbal.xml
  Resources/config/middlewares.xml
  Tests/DependencyInjection/Compiler/MiddlewarePassTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
Labels: Feature
