Repository doctrine/DoctrineBundle, pull requests merged in 2023-06, with the labels that each got.

#1671 Avoid indirect deprecations for the AttributeDriver in the testsuite
  Tests/DependencyInjection/Compiler/IdGeneratorPassTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  Tests/ServiceRepositoryTest.php
Labels: Test Suite

#1670 Expose a setting to opt-in for the XSD validation for mapping
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/schema/doctrine-1.0.xsd
  Resources/doc/configuration.rst
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/config/xml/orm_multiple_em_bundle_mappings.xml
  Tests/DependencyInjection/Fixtures/config/xml/orm_single_em_bundle_mappings.xml
  Tests/DependencyInjection/Fixtures/config/yml/orm_multiple_em_bundle_mappings.yml
  Tests/DependencyInjection/Fixtures/config/yml/orm_single_em_bundle_mappings.yml
  Tests/TestCase.php
  Tests/baseline-ignore
  UPGRADE-2.10.md
  phpunit.xml.dist
Labels: Improvement

#1676 Add a `priority` attribute on `doctrine.middleware` tag and `#[AsMiddleware]` attribute
  Attribute/AsMiddleware.php
  DependencyInjection/Compiler/MiddlewaresPass.php
  DependencyInjection/DoctrineExtension.php
  Resources/doc/middlewares.rst
  Tests/DependencyInjection/Compiler/MiddlewarePassTest.php
Labels: Feature

#1680 Fix SQL syntax highlight on Symfony 6.3
  Resources/views/Collector/db.html.twig
  Tests/ProfilerTest.php
Labels: Bug
