Repository doctrine/DoctrineBundle, pull requests merged in 2023-01, with the labels that each got.

#1607 Update Profiler UI for Symfony 6.2+.
  Resources/views/Collector/database.svg
  Resources/views/Collector/db.html.twig
Labels: Improvement

#1599 Make ServiceEntityRepository lazy on Symfony 6.2+
  Repository/LazyServiceEntityRepository.php
  Repository/ServiceEntityRepository.php
  Tests/Repository/ServiceEntityRepositoryTest.php
  phpcs.xml.dist
  psalm.xml.dist
Labels: Bug, Status: Needs Work

#1609 Add tabs to profiler UI.
  Resources/views/Collector/db.html.twig
Labels: Improvement

#1623 Fix registering PdoSessionHandlerSchemaSubscriber
  DependencyInjection/Compiler/CacheSchemaSubscriberPass.php
  DoctrineBundle.php
  Resources/config/orm.xml
Labels: Bug
