Repository doctrine/DoctrineBundle, pull requests merged in 2023-02, with the labels that each got.

#1626 Fix: Link to issue
  ConnectionFactory.php
Labels: Documentation

#1629 add priority argument to AsEntityListener attribute
  Attribute/AsEntityListener.php
  DependencyInjection/DoctrineExtension.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
Labels: Improvement

#1624 Allow to specify `EntityValueResolver` as `ValueResolver`
  Resources/config/orm.xml
Labels: Improvement, Status: On Hold

#1633 improve DoctrineDataCollectorTest and fix some deprecations
  DataCollector/DoctrineDataCollector.php
  Tests/DataCollector/DoctrineDataCollectorTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Labels: Improvement

#1632 allow configuring schema manager factory
  Command/CreateDatabaseDoctrineCommand.php
  Command/DropDatabaseDoctrineCommand.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/dbal.xml
  Resources/config/schema/doctrine-1.0.xsd
  Tests/Command/CreateDatabaseDoctrineTest.php
  Tests/Command/DropDatabaseDoctrineTest.php
  Tests/ConnectionFactoryTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Compiler/IdGeneratorPassTest.php
  Tests/DependencyInjection/Fixtures/TestKernel.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_schema_manager_factory.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_schema_manager_factory.yml
  Tests/Middleware/DebugMiddlewareTest.php
  Tests/ServiceRepositoryTest.php
  Tests/TestCase.php
  UPGRADE-2.9.md
  composer.json
Labels: Feature
