Repository doctrine/DoctrineBundle, pull requests merged in 2023-11, with the labels that each got.

#1724 Bump CI workflows
  .github/workflows/coding-standards.yml
  .github/workflows/composer-lint.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test-dev-stability.yml
Labels: CI

#1723 Doctrine CS 12
  Command/CreateDatabaseDoctrineCommand.php
  Command/DropDatabaseDoctrineCommand.php
  Command/ImportMappingDoctrineCommand.php
  Command/Proxy/ConvertMappingDoctrineCommand.php
  Command/Proxy/DoctrineCommandHelper.php
  Command/Proxy/OrmProxyCommand.php
  Command/Proxy/RunDqlDoctrineCommand.php
  Command/Proxy/RunSqlDoctrineCommand.php
  ConnectionFactory.php
  DependencyInjection/Compiler/CacheCompatibilityPass.php
  DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
  DependencyInjection/Compiler/EntityListenerPass.php
  DependencyInjection/Compiler/MiddlewaresPass.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Mapping/ContainerEntityListenerResolver.php
  Orm/ManagerRegistryAwareEntityManagerProvider.php
  Repository/ContainerRepositoryFactory.php
  Repository/LazyServiceEntityRepository.php
  Repository/ServiceEntityRepository.php
  Tests/Command/CreateDatabaseDoctrineTest.php
  Tests/Command/DropDatabaseDoctrineTest.php
  Tests/Command/ImportMappingDoctrineCommandTest.php
  Tests/Command/Proxy/InfoDoctrineCommandTest.php
  Tests/ConnectionFactoryTest.php
  Tests/Dbal/SchemaAssetsFilterManagerTest.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
  Tests/DependencyInjection/Compiler/MiddlewarePassTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/Bundles/AttributesBundle/Entity/TestCustomIdGeneratorEntity.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestCustomClassRepoEntity.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestCustomServiceRepoEntity.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestDefaultRepoEntity.php
  Tests/DependencyInjection/Fixtures/CustomEntityListenerServiceResolver.php
  Tests/DependencyInjection/Fixtures/CustomIdGenerator.php
  Tests/DependencyInjection/TestFilter.php
  Tests/DependencyInjection/TestType.php
  Tests/LockStoreSchemaListenerTest.php
  Tests/Mapping/DisconnectedMetadataFactoryTest.php
  Tests/Middleware/DebugMiddlewareTest.php
  Tests/ProfilerTest.php
  Tests/RegistryTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
  Tests/Repository/ServiceEntityRepositoryTest.php
  Tests/Twig/DoctrineExtensionTest.php
  Tests/UrlOverrideTest.php
  Twig/DoctrineExtension.php
  composer.json
Labels: Improvement

#1721 Extend dbal config and extension for result cache
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Resources/config/schema/doctrine-1.0.xsd
  Resources/doc/configuration.rst
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/config/xml/dbal_result_cache.xml
  Tests/DependencyInjection/Fixtures/config/yml/dbal_result_cache.yml
Labels: Feature

#1722 Compatibility with ORM 3
  DataCollector/DoctrineDataCollector.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineExtension.php
  Mapping/ContainerEntityListenerResolver.php
  Mapping/MappingDriver.php
  Repository/ContainerRepositoryFactory.php
  Repository/LazyServiceEntityRepository.php
  Repository/LegacyServiceEntityRepository.php
  Repository/RepositoryFactoryCompatibility.php
  Repository/ServiceEntityRepository.php
  Repository/ServiceEntityRepositoryProxy.php
  Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/DependencyInjection/DoctrineExtensionTest.php
  Tests/DependencyInjection/Fixtures/CustomEntityListenerServiceResolver.php
  Tests/DependencyInjection/Fixtures/CustomIdGenerator.php
  Tests/DependencyInjection/Fixtures/config/xml/orm_no_lazy_ghost.xml
  Tests/DependencyInjection/Fixtures/config/yml/orm_no_lazy_ghost.yml
  Tests/DependencyInjection/TestFilter.php
  Tests/Mapping/DisconnectedMetadataFactoryTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
  Tests/Repository/Fixtures/StubRepository.php
  Tests/Repository/Fixtures/StubServiceRepository.php
  composer.json
  phpcs.xml.dist
  psalm.xml.dist
Labels: Feature

#1726 Prepare the 2.11.0 release
  .doctrine-project.json
  .symfony.bundle.yaml
Labels: Documentation

#1731 Make deprecation warning about `enable_lazy_ghost_objects` more explicit
  DependencyInjection/DoctrineExtension.php
Labels: Improvement
