Repository doctrine/DoctrineBundle, pull requests merged in 2024-11, with the labels that each got.

#1832 Fix wiring of PHP metadata drivers on doctrine/orm 3.x
  composer.json
  psalm.xml.dist
  src/DependencyInjection/DoctrineExtension.php
  tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/DependencyInjection/Fixtures/config/xml/orm_multiple_em_bundle_mappings.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_single_em_bundle_mappings.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_single_em_default_table_options.xml
  tests/DependencyInjection/Fixtures/config/yml/orm_multiple_em_bundle_mappings.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_single_em_bundle_mappings.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_single_em_default_table_options.yml
Labels: Bug

#1834 docs: fix page for CustomIdGenerator attribute
  docs/en/custom-id-generators.rst
Labels: Documentation

#1840 Fix extraneous index:: in docs
  docs/en/configuration.rst
Labels: Documentation

#1841 Fix compatibility for Symfony 6 projects without doctrine/persistence 3 support
  composer.json
Labels: Bug

#1843 Use `kernel.build_dir` by default for proxy dir and metadata cache
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineExtension.php
  tests/CacheSchemaSubscriberTest.php
  tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  tests/DependencyInjection/Compiler/IdGeneratorPassTest.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/DependencyInjection/Fixtures/config/xml/orm_proxy.xml
  tests/LockStoreSchemaListenerTest.php
  tests/ServiceRepositoryTest.php
  tests/TestCase.php
Labels: Improvement
