Repository doctrine/DoctrineBundle, pull requests merged in 2024-05, with the labels that each got.

#1795 Update documentation for regex delimiters in schema_filter
  docs/configuration.rst
Labels: Documentation

#1796 Setup dependabot
  .github/dependabot.yml
  .github/workflows/continuous-integration.yml
Labels: CI

#1739 Register the idle connection listener
  config/dbal.xml
  config/middlewares.xml
  psalm.xml.dist
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineExtension.php
  src/Middleware/IdleConnectionMiddleware.php
  tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  tests/DependencyInjection/Compiler/MiddlewarePassTest.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/Middleware/IdleConnectionMiddlewareTest.php
Labels: Feature
