Repository doctrine/DoctrineBundle, pull requests merged in 2025-01, with the labels that each got.

#1851 There is no ProxyManagerBridge v7
  composer.json
Labels: Bug

#1850 Make doctrine/cache optional
  composer.json
Labels: Improvement

#1854 phpstan: lvl 1 -> 2
  phpstan.neon.dist
  src/Command/DoctrineCommand.php
  src/Command/ImportMappingDoctrineCommand.php
  src/ConnectionFactory.php
  src/Registry.php
Labels: Test Suite

#1859 bump to phpstan level 4
  phpstan.neon.dist
  src/CacheWarmer/DoctrineMetadataCacheWarmer.php
  src/Command/CreateDatabaseDoctrineCommand.php
  src/Command/DropDatabaseDoctrineCommand.php
  src/ConnectionFactory.php
  src/DataCollector/DoctrineDataCollector.php
  src/DependencyInjection/Compiler/WellKnownSchemaFilterPass.php
  src/DependencyInjection/DoctrineExtension.php
  src/DoctrineBundle.php
  src/Mapping/ClassMetadataFactory.php
  src/Twig/DoctrineExtension.php
  tests/DependencyInjection/AbstractDoctrineExtensionTest.php
  tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestCustomClassRepoEntity.php
  tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestCustomServiceRepoEntity.php
  tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Entity/TestDefaultRepoEntity.php
  tests/DependencyInjection/Fixtures/Bundles/YamlBundle/Entity/Test.php
  tests/Repository/ServiceEntityRepositoryTest.php
Labels: Improvement

#1863 feat: allow doctrine/persistence v4
  composer.json
  src/Mapping/MappingDriver.php
Labels: Improvement
