Repository doctrine/DoctrineBundle, pull requests merged in 2025-09, with the labels that each got.

#1919 Fix the tag definition for the 'doctrine.orm.entity_value_resolver' service
  config/orm.php
Labels: Bug

#1923 Drop support for doctrine/cache
  UPGRADE-3.0.md
  composer.json
  config/orm.php
  src/DependencyInjection/Compiler/CacheCompatibilityPass.php
  src/DoctrineBundle.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
  tests/DependencyInjection/Compiler/IdGeneratorPassTest.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/DependencyInjection/Fixtures/config/xml/orm_caches.xml
  tests/DependencyInjection/Fixtures/config/yml/orm_caches.yml
  tests/ServiceRepositoryTest.php
  tests/TestCase.php
Labels: BC Break

#1921 Update branch metadata
  .doctrine-project.json
  .github/workflows/website-schema.yml
  .symfony.bundle.yaml
Labels: CI

#1931 Lint config directory
  config/dbal.php
  config/messenger.php
  config/middlewares.php
  config/orm.php
  phpcs.xml.dist
Labels: Improvement

#1939 Remove DisconnectedMetadataFactory
  UPGRADE-3.0.md
  phpstan.neon.dist
  src/Mapping/DisconnectedMetadataFactory.php
  tests/Mapping/DisconnectedMetadataFactoryTest.php
Labels: BC Break

#1951 Avoid triggering unneeded CI jobs
  .github/workflows/coding-standards.yml
  .github/workflows/composer-lint.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
Labels: CI

#1957 Rely even less on YML in tests
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/Fixtures/config/xml/orm_functions.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_hydration_mode.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_identity_generation_preferences.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_imports_import.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_multiple_em_bundle_mappings.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_namingstrategy.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_quotestrategy.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_service_multiple_entity_managers.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_service_simple_single_entity_manager.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_service_simple_single_entity_manager_without_dbname.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_service_single_entity_manager.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_single_em_bundle_mappings.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_single_em_default_table_options.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_typedfieldmapper.xml
  tests/DependencyInjection/Fixtures/config/yml/orm_functions.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_hydration_mode.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_identity_generation_preferences.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_imports_import.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_multiple_em_bundle_mappings.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_namingstrategy.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_quotestrategy.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_service_multiple_entity_managers.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_service_simple_single_entity_manager.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_service_simple_single_entity_manager_without_dbname.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_service_single_entity_manager.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_single_em_bundle_mappings.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_single_em_default_table_options.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_typedfieldmapper.yml
Labels: Test Suite

#1954 Forget about report_fields_where_declared
  UPGRADE-3.0.md
  config/schema/doctrine-1.0.xsd
  docs/en/configuration.rst
  src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineExtension.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/Compiler/IdGeneratorPassTest.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/DependencyInjection/Fixtures/TestKernel.php
  tests/DependencyInjection/Fixtures/config/xml/orm_no_report_fields.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_report_fields.xml
  tests/DependencyInjection/Fixtures/config/yml/orm_no_report_fields.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_report_fields.yml
  tests/ServiceRepositoryTest.php
Labels: BC Break

#1969 Fix type error in Registry when no entity managers are configured
  config/dbal.php
Labels: Bug

#1973 Remove legacy group
  tests/RegistryTest.php
Labels: Test Suite

#1972 Remove unused types
  UPGRADE-3.0.md
  phpcs.xml.dist
  src/Repository/ContainerRepositoryFactory.php
  src/Repository/LazyServiceEntityRepository.php
  src/Repository/RepositoryFactoryCompatibility.php
  src/Repository/ServiceEntityRepository.php
  src/Repository/ServiceEntityRepositoryProxy.php
Labels: BC Break

#1975 Remove unused method
  src/Command/DoctrineCommand.php
Labels: Improvement

#1974 Remove DBAL 3 specific things
  docs/en/configuration.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineExtension.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
Labels: Improvement

#1976 Deprecate passing an event manager to CF::createConnection()
  UPGRADE-2.17.md
  src/ConnectionFactory.php
  src/DependencyInjection/DoctrineExtension.php
  tests/ConnectionFactoryTest.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
Labels: Deprecation

#1979 Remove type and method existence based checks
  UPGRADE-3.0.md
  src/ConnectionFactory.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineExtension.php
  tests/ConnectionFactoryTest.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/DoctrineExtensionTest.php
Labels: BC Break

#1989 Improve testdox output
  tests/DependencyInjection/XMLSchemaTest.php
Labels: Test Suite

#1990 Require ORM 3.4
  composer.json
  config/orm.php
  config/schema/doctrine-1.0.xsd
  docs/en/configuration.rst
  phpunit.xml.dist
  src/CacheWarmer/DoctrineMetadataCacheWarmer.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineExtension.php
  src/DoctrineBundle.php
  src/Registry.php
  tests/ContainerTest.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/Compiler/IdGeneratorPassTest.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/DependencyInjection/Fixtures/TestKernel.php
  tests/DependencyInjection/Fixtures/config/xml/orm_imports.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_imports_import.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_proxy.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_service_multiple_entity_managers.xml
  tests/DependencyInjection/Fixtures/config/xml/orm_service_single_entity_manager.xml
  tests/DependencyInjection/Fixtures/config/yml/orm_imports.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_imports_import.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_service_multiple_entity_managers.yml
  tests/DependencyInjection/Fixtures/config/yml/orm_service_single_entity_manager.yml
  tests/ServiceRepositoryTest.php
  tests/TestCase.php
  tests/baseline-ignore
Labels: BC Break

#1986 Remove LazyLoadingEntityManagerInterface
  composer.json
  tests/LazyLoadingEntityManagerInterface.php
Labels: Improvement

#1997 Remove deprecated method
  src/Twig/DoctrineExtension.php
  tests/Twig/DoctrineExtensionTest.php
Labels: Improvement

#1995 Remove URL override feature
  UPGRADE-3.0.md
  docs/en/configuration.rst
  src/ConnectionFactory.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineExtension.php
  tests/ConnectionFactoryTest.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/Fixtures/config/yml/dbal_allow_partial_url_override.yml
  tests/DependencyInjection/Fixtures/config/yml/dbal_allow_url_override.yml
  tests/UrlOverrideTest.php
Labels: BC Break

#2000 Avoid coverage upload for merge up pull requests
  .github/workflows/continuous-integration.yml
Labels: CI

#1999 Test without symfony/doctrine-messenger
  .github/workflows/continuous-integration.yml
Labels: CI

#2017 Migrate more PHPUnit attributes
  tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
  tests/DependencyInjection/Compiler/MiddlewarePassTest.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/LockStoreSchemaListenerTest.php
  tests/Middleware/IdleConnectionMiddlewareTest.php
Labels: Test Suite

#2022 Migrate to willReturn()
  tests/DataCollector/DoctrineDataCollectorTest.php
Labels: Test Suite

#2003 Remove deprecated interface and class
  UPGRADE-3.0.md
  config/dbal.php
  src/Dbal/BlacklistSchemaAssetFilter.php
  src/DependencyInjection/DoctrineExtension.php
  src/EventSubscriber/EventSubscriberInterface.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
Labels: BC Break

#2024 Use stubs when possible
  tests/Command/CreateDatabaseDoctrineTest.php
  tests/Command/DropDatabaseDoctrineTest.php
  tests/DataCollector/DoctrineDataCollectorTest.php
  tests/Repository/ContainerRepositoryFactoryTest.php
Labels: Test Suite

#2029 Fix erroneous order of events for multi events per listener
  src/DependencyInjection/Compiler/EntityListenerPass.php
  tests/DependencyInjection/Compiler/EntityListenerPassTest.php
Labels: Bug

#2048 Deprecate disable_type_comments
  UPGRADE-2.17.md
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
Labels: Deprecation

#2055 Deprecate use_savepoints when using DBAL 4
  UPGRADE-2.17.md
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/DoctrineExtensionTest.php
  tests/DependencyInjection/Fixtures/config/xml/dbal_use_savepoints.xml
  tests/DependencyInjection/Fixtures/config/yml/dbal_use_savepoints.yml
Labels: Deprecation

#2056 Cleanup XSD schema
  config/schema/doctrine-1.0.xsd
  tests/DependencyInjection/Fixtures/config/xml/dbal_allow_partial_url_override.xml
  tests/DependencyInjection/Fixtures/config/xml/dbal_allow_url_override.xml
Labels: BC Break

#2059 Remove useless existence check
  src/ConnectionFactory.php
Labels: Improvement

#2061 Remove useless comment
  tests/DependencyInjection/DoctrineExtensionTest.php
Labels: Improvement

#2066 Remove PHPStan ignore rule
  phpstan.neon.dist
Labels: Static Analysis

#2050 Remove .class parameters
  UPGRADE-3.0.md
  config/dbal.php
  config/orm.php
  src/DependencyInjection/DoctrineExtension.php
  tests/DependencyInjection/AbstractDoctrineExtensionTestCase.php
  tests/DependencyInjection/DoctrineExtensionTest.php
Labels: BC Break
